.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. monicoin_qt test_monicoin_qt
clean: FORCE
	$(MAKE) -C .. monicoin_qt_clean test_monicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_monicoin_qt_check
monicoin-qt monicoin-qt.exe: FORCE
	 $(MAKE) -C .. monicoin_qt
